### ISSUE TITLE
Throwing an error crashes solid start 0.4.6

### ISSUE THREAD

**Issue by shiro** [OrJDev/solid-start-trpc#2]
When throwing any error inside a handler using `@solidjs/start@0.4.6`, it crashes the server:

```
node:internal/deps/undici/undici:1331
      return new TypeError(`${message.header}: ${message.message}`);
             ^

TypeError: Response.clone: Body has already been consumed.
    at webidl.errors.exception (node:internal/deps/undici/undici:1331:14)
    at Response.clone (node:internal/deps/undici/undici:6734:31)
    at Object.stream (file:///opt/app/node_modules/solid-js/node_modules/seroval-plugins/dist/esm/production/web.mjs:1:7659)
    at U.parsePlugin (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:42116)
    at U.parseObject (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:36861)
    at U.parse (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:38342)
    at U.parseProperties (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:40988)
    at U.parsePlainObject (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:35802)
    at U.parseObject (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:36946)
    at U.parse (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:38342)
    at U.parseProperties (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:40988)
    at U.parseError (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:36112)
    at U.parseObject (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:37997)
    at U.parse (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:38342)
    at U.parseWithError (file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:42563)
    at file:///opt/app/node_modules/solid-js/node_modules/seroval/dist/esm/production/index.mjs:3:41729

Node.js v18.16.1
```

Returning a successful response works fine however.

If you think this is a start or vinxi issue, please let me know :bow:

**Comment by shiro** [comment]
After debugging, it seems to be a start/seroval issue, it only crashes in SSR (at the `fetch` call site), will prob. get resolved there after a while :rocket:
